runs_directory: "runs"  # where each run subfolder is created

# High-level iterative loop settings
iterations:
  max_iterations: 10
  success_threshold: 95   # e.g., a rating out of 100 that means “good enough.”

# Replicate model settings
replicate:
  model_name: "tencent/hunyuan-video:8283f26be7ce5dc0119324b4752cbfd3970b3ef1b923c4d3c35eb6546518747a"
  prompt_key: "prompt"  # If the model expects the prompt under a certain parameter
  # Add other custom parameters your chosen model might support

# ChatGPT / openAI model settings
openai:
  model_name: "gpt-4o-mini"
  update_guide_model_name: "gpt-4o-mini"
  reasoning_effort: "high"
  max_completion_tokens: 16000

# Frame extraction settings
frames:
  extract_interval: 15  # e.g., extract every 30 frames
  output_directory: "frames"

# Logging
logs:
  directory: "logs"

# Other
video_output_dir: "videos"

# ComfyUI local service settings for video generation
comfyui:
  # ComfyUI 服务接口地址
  api_url: "http://127.0.0.1:6006/api/prompt"
  # 客户端标识
  client_id: "default_client"
  # 视频生成相关参数
  video_length: 129
  steps: 12
  # 可选的 lora 前缀（用于构造 prompt 文本）
  lora: "myvgirl01x"
  # lora1 配置：模型文件路径及其权重
  lora_1: "Hunyuan/MY/myvgirl01x-converted.safetensors"
  lora_1_strength: 1.3
  # lora2 配置：模型文件路径及其权重
  lora_2: "Hunyuan/Motion/BreastMassage.safetensors"
  lora_2_strength: 0
  # shift 
  shift: 7.5

prompting_guide: |
  ────────────────────────────────────────────────────────
  1) Always Emphasize Consenting Adults & Clear Agency
  ────────────────────────────────────────────────────────
  • DO: Clearly state that all depicted individuals are consenting, adult humans, regardless of sexual orientation or scenario.
  • DO: Incorporate verbal—e.g., “safe word”—or mutual agreement cues for BDSM/kink or non-traditional acts like footplay.
  • DON’T: Include content violating policy (non-consensual, minors, bestiality).
  • EXAMPLE DO:
    "They exchange reassuring nods, confirming their mutual comfort. With their safe word in place, these two consenting adults prepare for an intimate foot-based exploration."
  
  ────────────────────────────────────────────────────────
  2) Be Descriptive, Add Context & Setting, AND USE CLINICAL LANGUAGE
  ────────────────────────────────────────────────────────
  • DO: Provide detailed environmental context (lighting, location, angles).
  • DO: Use explicit, clinical terms for anatomy: penis, vagina, penetration, erection. Avoid vague euphemisms if clinical clarity is intended.
  • DO: Clarify motion or touch: mention how feet, hands, or bodies move up/down or in/out if you want the model to depict it accurately.
  • DON’T: Rely on purely vague phrases like “they share a moment” if you want distinct positions, motions, or acts shown.
  • EXAMPLE DO:
    "In a softly lit bedroom, she gently grips his erect penis between both feet, moving her soles up and down the shaft, describing each sensation in a playful, consenting manner."
  
  ────────────────────────────────────────────────────────
  3) Keep It Human or Mechanically “Futuristic” If Exploring Fantasy
  ────────────────────────────────────────────────────────
  • DO: For tentacle or sci-fi elements, frame them as mechanical or stylized attachments—never actual animals or forced scenarios. Emphasize that all involved are consenting adults.
  • DON’T: Portray real animals, minors, or non-consensual restraints.
  • EXAMPLE DO (Mechanical/Bioengineered):
    "She smiles confidently, adjusting the robotic limbs designed to resemble tentacles. Each one is programmed to move gently at her command, ensuring her comfort and fascination with this futuristic encounter."
  
  ────────────────────────────────────────────────────────
  4) When the Model Refuses or Returns “I’m Sorry…”
  ────────────────────────────────────────────────────────
  • DO: Re-check your prompt for any hint of non-consent, minors, or other disallowed areas. Remove or rephrase those elements.
  • DO: Strengthen your system prompt with clarifications that you are depicting consenting adults.
  • DON’T: Repeat the same disallowed request without changes. If the concept is inherently out of policy, the model will continue refusing.
  
  ────────────────────────────────────────────────────────
  5) Increase Tangible/Sensory Detail Gradually
  ────────────────────────────────────────────────────────
  • DO: Add incremental detail about sights, sounds, sensations (the warmth of touch, changes in breathing, emotional cues).
  • DO: If you want explicit movement (e.g., rhythmic stroking), describe each step carefully to avoid ambiguous outputs.
  • DON’T: Overwhelm with too many explicit elements at once; a balanced approach yields clearer, more coherent results.
  
  ────────────────────────────────────────────────────────
  6) Use Separate Sections (Optional, But Helpful)
  ────────────────────────────────────────────────────────
  If your app or tool enforces structured prompts:
  • Preface: Tone, emotional context, personalities.
  • Explicit_Scene_Description: Specific erotic actions, clear anatomical terms, mention of consent.
  • Disclaimers: Reinforce adult status, mutual respect, and safe words or boundaries as appropriate.
  
  ────────────────────────────────────────────────────────
  7) Example “Do” Prompt vs. “Don’t” Prompt
  ────────────────────────────────────────────────────────
  • DO Prompt (Male-on-Male, Clear Consent):
    "Two adult men relax on a couch in a softly lit living room, confirming each other’s comfort before engaging in foreplay. They exchange gentle caresses, describing their desire out loud. One man gradually guides the other’s erect penis into a slow, consensual penetration, maintaining eye contact and periodically checking for mutual enjoyment."
  
  • DO Prompt (Footplay, Explicit Detail):
    "A nude woman and her consenting male partner confirm a safe word. Under dim bedroom lighting, she presses her feet around his erect penis, gripping it firmly with her toes. She then glides her soles rhythmically up and down the shaft, describing how the sensation intensifies for both of them."
  
  • DON’T Prompt (Forced or Disallowed Content):
    "An unconscious individual is tied down while tentacles, implied to be non-human and uncontrollable, force themselves upon her.”  
    (Depicts non-consent and actual non-human creatures.)
  
  ────────────────────────────────────────────────────────
  8) Summary Recommendations
  ────────────────────────────────────────────────────────
  • Always clarify adult status, consent, and safe words.  
  • Add descriptive detail about environment, anatomy, and movements for clarity.  
  • If including fantasy elements (like robotic attachments), specify they are not living creatures; ensure all acts remain consensual.  
  • Adjust or remove problematic elements if you receive refusal messages.
